apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: longhorn
  repo: https://charts.longhorn.io
  version: 1.3.0
  releaseName: longhorn
  namespace: longhorn
  valuesFile: values.yaml