apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: loki-stack
  repo: https://grafana.github.io/helm-charts
  version: 2.6.5
  releaseName: loki
  namespace: monitoring
  valuesFile: loki-values.yaml

- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: false
  version: 36.2.0
  releaseName: prometheus
  namespace: monitoring
  valuesFile: prom-values.yaml
