apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization  

resources:
- github.com/kubernetes-csi/external-snapshotter/tree/v6.3.2/client/config/crd?ref=v7.0.1
- github.com/kubernetes-csi/external-snapshotter/tree/v6.3.2/deploy/kubernetes/snapshot-controller?ref=v7.0.1
- snapshotclass.yaml