apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization  

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.10.1
- ingress.yaml

patches:
- path: server-insecure.yaml
- path: kustomize-enable-helm.yaml