apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.longhorn.io'
    chart: longhorn
    targetRevision: v1.6.0
    helm:
      valueFiles:
      - $values/longhorn/values.yaml
  - repoURL: 'https://github.com/shriker95/kubernetes.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true